# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/Rohit/Downloads/constraints_slave_final.xdc

# Block Designs: bd/slave/slave.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==slave || ORIG_REF_NAME==slave} -quiet] -quiet

# IP: bd/slave/ip/slave_axi_interconnect_0_imp_xbar_0/slave_axi_interconnect_0_imp_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==slave_axi_interconnect_0_imp_xbar_0 || ORIG_REF_NAME==slave_axi_interconnect_0_imp_xbar_0} -quiet] -quiet

# IP: bd/slave/ip/slave_axi_interconnect_0_0/slave_axi_interconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==slave_axi_interconnect_0_0 || ORIG_REF_NAME==slave_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/slave/ip/slave_axi_uartlite_0_0/slave_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==slave_axi_uartlite_0_0 || ORIG_REF_NAME==slave_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/slave/ip/slave_axi_uartlite_0_1/slave_axi_uartlite_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==slave_axi_uartlite_0_1 || ORIG_REF_NAME==slave_axi_uartlite_0_1} -quiet] -quiet

# IP: bd/slave/ip/slave_axi_uartlite_1_0/slave_axi_uartlite_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==slave_axi_uartlite_1_0 || ORIG_REF_NAME==slave_axi_uartlite_1_0} -quiet] -quiet

# IP: bd/slave/ip/slave_axi_uartlite_2_0/slave_axi_uartlite_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==slave_axi_uartlite_2_0 || ORIG_REF_NAME==slave_axi_uartlite_2_0} -quiet] -quiet

# IP: bd/slave/ip/slave_axi_quad_spi_0_0/slave_axi_quad_spi_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==slave_axi_quad_spi_0_0 || ORIG_REF_NAME==slave_axi_quad_spi_0_0} -quiet] -quiet

# IP: bd/slave/ip/slave_axi_quad_spi_0_1/slave_axi_quad_spi_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==slave_axi_quad_spi_0_1 || ORIG_REF_NAME==slave_axi_quad_spi_0_1} -quiet] -quiet

# IP: bd/slave/ip/slave_axi_quad_spi_1_0/slave_axi_quad_spi_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==slave_axi_quad_spi_1_0 || ORIG_REF_NAME==slave_axi_quad_spi_1_0} -quiet] -quiet

# IP: bd/slave/ip/slave_axi_quad_spi_2_0/slave_axi_quad_spi_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==slave_axi_quad_spi_2_0 || ORIG_REF_NAME==slave_axi_quad_spi_2_0} -quiet] -quiet

# IP: bd/slave/ip/slave_axi_gpio_0_0/slave_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==slave_axi_gpio_0_0 || ORIG_REF_NAME==slave_axi_gpio_0_0} -quiet] -quiet

# IP: bd/slave/ip/slave_axi_timer_0_0/slave_axi_timer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==slave_axi_timer_0_0 || ORIG_REF_NAME==slave_axi_timer_0_0} -quiet] -quiet

# IP: bd/slave/ip/slave_xlconcat_0_0/slave_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==slave_xlconcat_0_0 || ORIG_REF_NAME==slave_xlconcat_0_0} -quiet] -quiet

# IP: bd/slave/ip/slave_axi_intc_0_0/slave_axi_intc_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==slave_axi_intc_0_0 || ORIG_REF_NAME==slave_axi_intc_0_0} -quiet] -quiet

# IP: bd/slave/ip/slave_microblaze_0_0/slave_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==slave_microblaze_0_0 || ORIG_REF_NAME==slave_microblaze_0_0} -quiet] -quiet

# IP: bd/slave/ip/slave_dlmb_v10_0/slave_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==slave_dlmb_v10_0 || ORIG_REF_NAME==slave_dlmb_v10_0} -quiet] -quiet

# IP: bd/slave/ip/slave_ilmb_v10_0/slave_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==slave_ilmb_v10_0 || ORIG_REF_NAME==slave_ilmb_v10_0} -quiet] -quiet

# IP: bd/slave/ip/slave_dlmb_bram_if_cntlr_0/slave_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==slave_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==slave_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/slave/ip/slave_ilmb_bram_if_cntlr_0/slave_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==slave_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==slave_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/slave/ip/slave_lmb_bram_0/slave_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==slave_lmb_bram_0 || ORIG_REF_NAME==slave_lmb_bram_0} -quiet] -quiet

# IP: bd/slave/ip/slave_mdm_1_0/slave_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==slave_mdm_1_0 || ORIG_REF_NAME==slave_mdm_1_0} -quiet] -quiet

# IP: bd/slave/ip/slave_clk_wiz_1_0/slave_clk_wiz_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==slave_clk_wiz_1_0 || ORIG_REF_NAME==slave_clk_wiz_1_0} -quiet] -quiet

# IP: bd/slave/ip/slave_rst_clk_wiz_1_100M_0/slave_rst_clk_wiz_1_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==slave_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==slave_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/slave/ip/slave_axi_bram_ctrl_0_0/slave_axi_bram_ctrl_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==slave_axi_bram_ctrl_0_0 || ORIG_REF_NAME==slave_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/slave/ip/slave_blk_mem_gen_0_0/slave_blk_mem_gen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==slave_blk_mem_gen_0_0 || ORIG_REF_NAME==slave_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/slave/ip/slave_axi_quad_spi_4_0/slave_axi_quad_spi_4_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==slave_axi_quad_spi_4_0 || ORIG_REF_NAME==slave_axi_quad_spi_4_0} -quiet] -quiet

# IP: bd/slave/ip/slave_axi_interconnect_0_imp_auto_pc_0/slave_axi_interconnect_0_imp_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==slave_axi_interconnect_0_imp_auto_pc_0 || ORIG_REF_NAME==slave_axi_interconnect_0_imp_auto_pc_0} -quiet] -quiet

# XDC: c:/Rohit/project_1/project_1.gen/sources_1/bd/slave/slave_ooc.xdc
